def show_menu():
    print("\n════════════ MENU ════════════")
    print("           MENU CARD")
    print("══════════════════════════════")

    print("\nCOMBO :")
    print("1  Combo Shahi Thali        : ₹600")

    print("\nSTARTERS :")
    print("2  Masala papad             : ₹15")
    print("3  Dhokla                   : ₹60")
    print("4  Sweet Corn Chaat         : ₹90")
    print("5  Masala Peanuts           : ₹70")
    print("6  Steamed Momos            : ₹50")
    print("7  Aloo Tikki               : ₹120")
    print("8  Veg Soup                 : ₹70")
    print("9  Egg Bhurji               : ₹110")
    print("10 Chicken Steam Momos      : ₹180")
    print("11  Chicken Soup            : ₹120")

    print("\nRICE & BIRYANI :")
    print("12 Veg Plain Rice           : ₹180")
    print("13 Biryani                  : ₹200")

    print("\nBREAKFAST :")
    print("14 Tandoor Roti             : ₹180")
    print("15 Aloo Paratha             : ₹120")

    print("\nSOUTH INDIAN :")
    print("16 Medu Vada                : ₹90")
    print("17 Rava Dosa                : ₹150")

    print("\nDESSERTS :")
    print("18 Jalebi                   : ₹50")
    print("19 Rasmalai                 : ₹90")

    print("\nBEVERAGES :")
    print("20 Apple Juice              : ₹40")
    print("21 Sweet Lassi              : ₹70")
    print("22 Cold Coffee              : ₹100")
    print("23 Masala Chai              : ₹50")
    print("24 Fresh Lime Soda          : ₹80")
    print("25 Mango Lassi              : ₹100")

    print("\nMORE STARTERS :")
    print("26 Hara Bhara Kabab         : ₹180")
    print("27 Paneer Tikka             : ₹280")
    print("28 Veg Spring Roll          : ₹160")
    print("29 French Fries             : ₹140")
    print("30 Chilli Paneer            : ₹260")
    print("31 Veg Manchurian           : ₹220")
    print("32 Honey Chilli Potato      : ₹200")

    print("\nMORE MAIN COURSE :")
    print("33 Kadhai Paneer            : ₹280")
    print("34 Shahi Paneer             : ₹300")
    print("35 Mix Veg                  : ₹220")
    print("36 Butter Naan              : ₹70")
    print("37 Garlic Naan              : ₹90")
    print("38 Plain Naan               : ₹50")
    print("39 Laccha Paratha           : ₹80")
    print("40 Jeera Rice               : ₹180")
    print("41 Dal Tadka                : ₹190")
    print("42 Veg Pulao                : ₹200")

    print("\nSPECIAL ITEMS :")
    print("43 Hyderabadi Biryani       : ₹350")
    print("44 Tandoori Platter         : ₹550")
    print("45 Paneer Roll              : ₹180")
    print("46 Veg Sandwich             : ₹150")
    print("47 Veg Burger               : ₹180")
    print("48 Pizza                    : ₹350")

    print("\nDESSERTS :")
    print("49 Ice Cream                : ₹100")
    print("50 Brownie                  : ₹180")

    print("══════════════════════════════")
